### ISSUE TITLE
Use a format preserving TOML parser

### ISSUE THREAD

**Issue by egilsster** [egilsster/git-releaser#94]
Currently it changes
```toml
tokio = { version = "0.2.25", features = ["rt-threaded", "macros"] }
```

to

```toml
[dependencies.tokio]
version = "0.2.25"
features = ["rt-threaded", "macros"]
```
which is not nice.

Since I am only changing the version value for the source crate it should preserve the formatting of everything else.
